/**
 * Central registry for all tlang node types
 *
 * AUTO-GENERATED by scripts/generate-registry.js
 * DO NOT EDIT MANUALLY - it will be overwritten
 *
 * Single Source of Truth: tlang/src/
 * Generated at: 2026-01-05T07:24:24.168Z
 */

import type { TLangNodeMetadata } from '../../types/node'

/**
 * Complete registry of all tlang nodes
 */
export const nodeRegistry: Record<string, TLangNodeMetadata> = {
  'Unions.UnionKeys': {
    id: 'Unions.UnionKeys',
    name: 'UnionKeys',
    category: 'Unions',
    description: 'UnionKeysNode - Extract all possible keys from a union',
    inputs: [
      { id: 'in', label: 'In', type: 'any', required: true }
    ],
    outputs: [
      { id: 'out', label: 'Out', type: 'any', required: false }
    ],
    tlangType: 'Unions.UnionKeys',
    style: { color: '#ec4899' }
  },

  'Unions.UnionToIntersection': {
    id: 'Unions.UnionToIntersection',
    name: 'UnionToIntersection',
    category: 'Unions',
    description: 'UnionToIntersectionNode - Convert union to intersection',
    inputs: [
      { id: 'in', label: 'In', type: 'any', required: true }
    ],
    outputs: [
      { id: 'out', label: 'Out', type: 'any', required: false }
    ],
    tlangType: 'Unions.UnionToIntersection',
    style: { color: '#ec4899' }
  },

  'Unions.ExcludeUnion': {
    id: 'Unions.ExcludeUnion',
    name: 'ExcludeUnion',
    category: 'Unions',
    description: 'ExcludeUnionNode - Remove specific types from a union',
    inputs: [
      { id: 'in', label: 'In', type: 'any', required: true }
    ],
    outputs: [
      { id: 'out', label: 'Out', type: 'any', required: false }
    ],
    tlangType: 'Unions.ExcludeUnion',
    style: { color: '#ec4899' }
  },

  'Unions.ExtractUnion': {
    id: 'Unions.ExtractUnion',
    name: 'ExtractUnion',
    category: 'Unions',
    description: 'ExtractUnionNode - Keep only specific types from a union',
    inputs: [
      { id: 'in', label: 'In', type: 'any', required: true }
    ],
    outputs: [
      { id: 'out', label: 'Out', type: 'any', required: false }
    ],
    tlangType: 'Unions.ExtractUnion',
    style: { color: '#ec4899' }
  },

  'Unions.UnionMap': {
    id: 'Unions.UnionMap',
    name: 'UnionMap',
    category: 'Unions',
    description: 'UnionMapNode - Map a transformation over each member of a union',
    inputs: [
      { id: 'in', label: 'In', type: 'any', required: true }
    ],
    outputs: [
      { id: 'out', label: 'Out', type: 'object', required: false }
    ],
    tlangType: 'Unions.UnionMap',
    style: { color: '#ec4899' }
  },

  'Tuples.Map': {
    id: 'Tuples.Map',
    name: 'Map',
    category: 'Tuples',
    description: 'MapNode - Transform each element in a tuple',
    inputs: [
      { id: 'in', label: 'In', type: 'any', required: true }
    ],
    outputs: [
      { id: 'out', label: 'Out', type: 'any', required: false }
    ],
    tlangType: 'Tuples.Map',
    style: { color: '#ec4899' }
  },

  'Tuples.Filter': {
    id: 'Tuples.Filter',
    name: 'Filter',
    category: 'Tuples',
    description: 'FilterNode - Keep only elements that satisfy a predicate',
    inputs: [
      { id: 'in', label: 'In', type: 'any', required: true }
    ],
    outputs: [
      { id: 'out', label: 'Out', type: 'any', required: false }
    ],
    tlangType: 'Tuples.Filter',
    style: { color: '#ec4899' }
  },

  'Tuples.Head': {
    id: 'Tuples.Head',
    name: 'Head',
    category: 'Tuples',
    description: 'HeadNode - Get the first element of a tuple',
    inputs: [
      { id: 'in', label: 'In', type: 'any', required: true }
    ],
    outputs: [
      { id: 'out', label: 'Out', type: 'any', required: false }
    ],
    tlangType: 'Tuples.Head',
    style: { color: '#ec4899' }
  },

  'Tuples.Tail': {
    id: 'Tuples.Tail',
    name: 'Tail',
    category: 'Tuples',
    description: 'TailNode - Get all elements except the first',
    inputs: [
      { id: 'in', label: 'In', type: 'any', required: true }
    ],
    outputs: [
      { id: 'out', label: 'Out', type: 'any', required: false }
    ],
    tlangType: 'Tuples.Tail',
    style: { color: '#ec4899' }
  },

  'Tuples.Last': {
    id: 'Tuples.Last',
    name: 'Last',
    category: 'Tuples',
    description: 'LastNode - Get the last element of a tuple',
    inputs: [
      { id: 'in', label: 'In', type: 'any', required: true }
    ],
    outputs: [
      { id: 'out', label: 'Out', type: 'any', required: false }
    ],
    tlangType: 'Tuples.Last',
    style: { color: '#ec4899' }
  },

  'Tuples.At': {
    id: 'Tuples.At',
    name: 'At',
    category: 'Tuples',
    description: 'AtNode - Get element at specific index',
    inputs: [
      { id: 'in', label: 'In', type: 'any', required: true }
    ],
    outputs: [
      { id: 'out', label: 'Out', type: 'any', required: false }
    ],
    tlangType: 'Tuples.At',
    style: { color: '#ec4899' }
  },

  'Tuples.Concat': {
    id: 'Tuples.Concat',
    name: 'Concat',
    category: 'Tuples',
    description: 'ConcatNode - Concatenate two tuples',
    inputs: [
      { id: 'in', label: 'In', type: 'any', required: true }
    ],
    outputs: [
      { id: 'out', label: 'Out', type: 'any', required: false }
    ],
    tlangType: 'Tuples.Concat',
    style: { color: '#ec4899' }
  },

  'Tuples.Reverse': {
    id: 'Tuples.Reverse',
    name: 'Reverse',
    category: 'Tuples',
    description: 'ReverseNode - Reverse a tuple',
    inputs: [
      { id: 'in', label: 'In', type: 'any', required: true }
    ],
    outputs: [
      { id: 'out', label: 'Out', type: 'any', required: false }
    ],
    tlangType: 'Tuples.Reverse',
    style: { color: '#ec4899' }
  },

  'Tuples.ToUnion': {
    id: 'Tuples.ToUnion',
    name: 'ToUnion',
    category: 'Tuples',
    description: 'ToUnionNode - Convert tuple to union',
    inputs: [
      { id: 'in', label: 'In', type: 'any', required: true }
    ],
    outputs: [
      { id: 'out', label: 'Out', type: 'any', required: false }
    ],
    tlangType: 'Tuples.ToUnion',
    style: { color: '#ec4899' }
  },

  'Tuples.ToIntersection': {
    id: 'Tuples.ToIntersection',
    name: 'ToIntersection',
    category: 'Tuples',
    description: 'ToIntersectionNode - Convert tuple to intersection',
    inputs: [
      { id: 'in', label: 'In', type: 'any', required: true }
    ],
    outputs: [
      { id: 'out', label: 'Out', type: 'any', required: false }
    ],
    tlangType: 'Tuples.ToIntersection',
    style: { color: '#ec4899' }
  },

  'Tuples.Length': {
    id: 'Tuples.Length',
    name: 'Length',
    category: 'Tuples',
    description: 'LengthNode - Get tuple length',
    inputs: [
      { id: 'in', label: 'In', type: 'any', required: true }
    ],
    outputs: [
      { id: 'out', label: 'Out', type: 'any', required: false }
    ],
    tlangType: 'Tuples.Length',
    style: { color: '#ec4899' }
  },

  'Tuples.IsEmpty': {
    id: 'Tuples.IsEmpty',
    name: 'IsEmpty',
    category: 'Tuples',
    description: 'IsEmptyNode - Check if tuple is empty',
    inputs: [
      { id: 'in', label: 'In', type: 'any', required: true }
    ],
    outputs: [
      { id: 'out', label: 'Out', type: 'any', required: false }
    ],
    tlangType: 'Tuples.IsEmpty',
    style: { color: '#ec4899' }
  },

  'Tuples.Prepend': {
    id: 'Tuples.Prepend',
    name: 'Prepend',
    category: 'Tuples',
    description: 'PrependNode - Add element to beginning',
    inputs: [
      { id: 'in', label: 'In', type: 'any', required: true }
    ],
    outputs: [
      { id: 'out', label: 'Out', type: 'any', required: false }
    ],
    tlangType: 'Tuples.Prepend',
    style: { color: '#ec4899' }
  },

  'Tuples.Append': {
    id: 'Tuples.Append',
    name: 'Append',
    category: 'Tuples',
    description: 'AppendNode - Add element to end',
    inputs: [
      { id: 'in', label: 'In', type: 'any', required: true }
    ],
    outputs: [
      { id: 'out', label: 'Out', type: 'any', required: false }
    ],
    tlangType: 'Tuples.Append',
    style: { color: '#ec4899' }
  },

  'Tuples.Join': {
    id: 'Tuples.Join',
    name: 'Join',
    category: 'Tuples',
    description: 'JoinNode - Join tuple elements into string',
    inputs: [
      { id: 'in', label: 'In', type: 'any', required: true }
    ],
    outputs: [
      { id: 'out', label: 'Out', type: 'any', required: false }
    ],
    tlangType: 'Tuples.Join',
    style: { color: '#ec4899' }
  },

  'Tuples.Reduce': {
    id: 'Tuples.Reduce',
    name: 'Reduce',
    category: 'Tuples',
    description: 'ReduceNode - Reduce tuple to single value',
    inputs: [
      { id: 'in', label: 'In', type: 'any', required: true }
    ],
    outputs: [
      { id: 'out', label: 'Out', type: 'any', required: false }
    ],
    tlangType: 'Tuples.Reduce',
    style: { color: '#ec4899' }
  },

  'Strings.Length': {
    id: 'Strings.Length',
    name: 'Length',
    category: 'Strings',
    description: 'LengthNode - Get the length of a string',
    inputs: [
      { id: 'in', label: 'In', type: 'any', required: true }
    ],
    outputs: [
      { id: 'out', label: 'Out', type: 'any', required: false }
    ],
    tlangType: 'Strings.Length',
    style: { color: '#10b981' }
  },

  'Strings.Split': {
    id: 'Strings.Split',
    name: 'Split',
    category: 'Strings',
    description: 'SplitNode - Split a string into a tuple',
    inputs: [
      { id: 'in', label: 'In', type: 'any', required: true }
    ],
    outputs: [
      { id: 'out', label: 'Out', type: 'any', required: false }
    ],
    tlangType: 'Strings.Split',
    style: { color: '#10b981' }
  },

  'Strings.ToTuple': {
    id: 'Strings.ToTuple',
    name: 'ToTuple',
    category: 'Strings',
    description: 'ToTupleNode - Convert string to tuple of characters',
    inputs: [
      { id: 'in', label: 'In', type: 'any', required: true }
    ],
    outputs: [
      { id: 'out', label: 'Out', type: 'any', required: false }
    ],
    tlangType: 'Strings.ToTuple',
    style: { color: '#10b981' }
  },

  'Strings.ToString': {
    id: 'Strings.ToString',
    name: 'ToString',
    category: 'Strings',
    description: 'ToStringNode - Convert stringifiable to string',
    inputs: [
      { id: 'in', label: 'In', type: 'any', required: true }
    ],
    outputs: [
      { id: 'out', label: 'Out', type: 'object', required: false }
    ],
    tlangType: 'Strings.ToString',
    style: { color: '#10b981' }
  },

  'Strings.ToNumber': {
    id: 'Strings.ToNumber',
    name: 'ToNumber',
    category: 'Strings',
    description: 'ToNumberNode - Convert string to number or bigint',
    inputs: [
      { id: 'in', label: 'In', type: 'any', required: true }
    ],
    outputs: [
      { id: 'out', label: 'Out', type: 'any', required: false }
    ],
    tlangType: 'Strings.ToNumber',
    style: { color: '#10b981' }
  },

  'Strings.Prepend': {
    id: 'Strings.Prepend',
    name: 'Prepend',
    category: 'Strings',
    description: 'PrependNode - Prepend string to input',
    inputs: [
      { id: 'in', label: 'In', type: 'any', required: true }
    ],
    outputs: [
      { id: 'out', label: 'Out', type: 'object', required: false }
    ],
    tlangType: 'Strings.Prepend',
    style: { color: '#10b981' }
  },

  'Strings.Append': {
    id: 'Strings.Append',
    name: 'Append',
    category: 'Strings',
    description: 'AppendNode - Append string to input',
    inputs: [
      { id: 'in', label: 'In', type: 'any', required: true }
    ],
    outputs: [
      { id: 'out', label: 'Out', type: 'object', required: false }
    ],
    tlangType: 'Strings.Append',
    style: { color: '#10b981' }
  },

  'Strings.Uppercase': {
    id: 'Strings.Uppercase',
    name: 'Uppercase',
    category: 'Strings',
    description: 'UppercaseNode - Transform string to uppercase',
    inputs: [
      { id: 'in', label: 'In', type: 'any', required: true }
    ],
    outputs: [
      { id: 'out', label: 'Out', type: 'string', required: false }
    ],
    tlangType: 'Strings.Uppercase',
    style: { color: '#10b981' }
  },

  'Strings.Lowercase': {
    id: 'Strings.Lowercase',
    name: 'Lowercase',
    category: 'Strings',
    description: 'LowercaseNode - Transform string to lowercase',
    inputs: [
      { id: 'in', label: 'In', type: 'any', required: true }
    ],
    outputs: [
      { id: 'out', label: 'Out', type: 'string', required: false }
    ],
    tlangType: 'Strings.Lowercase',
    style: { color: '#10b981' }
  },

  'Strings.Capitalize': {
    id: 'Strings.Capitalize',
    name: 'Capitalize',
    category: 'Strings',
    description: 'CapitalizeNode - Capitalize first character',
    inputs: [
      { id: 'in', label: 'In', type: 'any', required: true }
    ],
    outputs: [
      { id: 'out', label: 'Out', type: 'string', required: false }
    ],
    tlangType: 'Strings.Capitalize',
    style: { color: '#10b981' }
  },

  'Strings.Uncapitalize': {
    id: 'Strings.Uncapitalize',
    name: 'Uncapitalize',
    category: 'Strings',
    description: 'UncapitalizeNode - Uncapitalize first character',
    inputs: [
      { id: 'in', label: 'In', type: 'any', required: true }
    ],
    outputs: [
      { id: 'out', label: 'Out', type: 'string', required: false }
    ],
    tlangType: 'Strings.Uncapitalize',
    style: { color: '#10b981' }
  },

  'Strings.Trim': {
    id: 'Strings.Trim',
    name: 'Trim',
    category: 'Strings',
    description: 'TrimNode - Trim whitespace from both sides',
    inputs: [
      { id: 'in', label: 'In', type: 'any', required: true }
    ],
    outputs: [
      { id: 'out', label: 'Out', type: 'any', required: false }
    ],
    tlangType: 'Strings.Trim',
    style: { color: '#10b981' }
  },

  'Strings.TrimLeft': {
    id: 'Strings.TrimLeft',
    name: 'TrimLeft',
    category: 'Strings',
    description: 'TrimLeftNode - Trim whitespace from left side',
    inputs: [
      { id: 'in', label: 'In', type: 'any', required: true }
    ],
    outputs: [
      { id: 'out', label: 'Out', type: 'any', required: false }
    ],
    tlangType: 'Strings.TrimLeft',
    style: { color: '#10b981' }
  },

  'Strings.TrimRight': {
    id: 'Strings.TrimRight',
    name: 'TrimRight',
    category: 'Strings',
    description: 'TrimRightNode - Trim whitespace from right side',
    inputs: [
      { id: 'in', label: 'In', type: 'any', required: true }
    ],
    outputs: [
      { id: 'out', label: 'Out', type: 'any', required: false }
    ],
    tlangType: 'Strings.TrimRight',
    style: { color: '#10b981' }
  },

  'Strings.Replace': {
    id: 'Strings.Replace',
    name: 'Replace',
    category: 'Strings',
    description: 'ReplaceNode - Replace all occurrences of substring',
    inputs: [
      { id: 'in', label: 'In', type: 'any', required: true }
    ],
    outputs: [
      { id: 'out', label: 'Out', type: 'any', required: false }
    ],
    tlangType: 'Strings.Replace',
    style: { color: '#10b981' }
  },

  'Strings.Repeat': {
    id: 'Strings.Repeat',
    name: 'Repeat',
    category: 'Strings',
    description: 'RepeatNode - Repeat string N times',
    inputs: [
      { id: 'in', label: 'In', type: 'any', required: true }
    ],
    outputs: [
      { id: 'out', label: 'Out', type: 'any', required: false }
    ],
    tlangType: 'Strings.Repeat',
    style: { color: '#10b981' }
  },

  'Strings.StartsWith': {
    id: 'Strings.StartsWith',
    name: 'StartsWith',
    category: 'Strings',
    description: 'StartsWithNode - Check if string starts with substring',
    inputs: [
      { id: 'in', label: 'In', type: 'any', required: true }
    ],
    outputs: [
      { id: 'out', label: 'Out', type: 'any', required: false }
    ],
    tlangType: 'Strings.StartsWith',
    style: { color: '#10b981' }
  },

  'Strings.EndsWith': {
    id: 'Strings.EndsWith',
    name: 'EndsWith',
    category: 'Strings',
    description: 'EndsWithNode - Check if string ends with substring',
    inputs: [
      { id: 'in', label: 'In', type: 'any', required: true }
    ],
    outputs: [
      { id: 'out', label: 'Out', type: 'any', required: false }
    ],
    tlangType: 'Strings.EndsWith',
    style: { color: '#10b981' }
  },

  'Strings.Includes': {
    id: 'Strings.Includes',
    name: 'Includes',
    category: 'Strings',
    description: 'IncludesNode - Check if string contains substring',
    inputs: [
      { id: 'in', label: 'In', type: 'any', required: true }
    ],
    outputs: [
      { id: 'out', label: 'Out', type: 'any', required: false }
    ],
    tlangType: 'Strings.Includes',
    style: { color: '#10b981' }
  },

  'Strings.CamelCase': {
    id: 'Strings.CamelCase',
    name: 'CamelCase',
    category: 'Strings',
    description: 'CamelCaseNode - Convert to camelCase',
    inputs: [
      { id: 'in', label: 'In', type: 'any', required: true }
    ],
    outputs: [
      { id: 'out', label: 'Out', type: 'any', required: false }
    ],
    tlangType: 'Strings.CamelCase',
    style: { color: '#10b981' }
  },

  'Strings.SnakeCase': {
    id: 'Strings.SnakeCase',
    name: 'SnakeCase',
    category: 'Strings',
    description: 'SnakeCaseNode - Convert to snake_case',
    inputs: [
      { id: 'in', label: 'In', type: 'any', required: true }
    ],
    outputs: [
      { id: 'out', label: 'Out', type: 'any', required: false }
    ],
    tlangType: 'Strings.SnakeCase',
    style: { color: '#10b981' }
  },

  'Strings.KebabCase': {
    id: 'Strings.KebabCase',
    name: 'KebabCase',
    category: 'Strings',
    description: 'KebabCaseNode - Convert to kebab-case',
    inputs: [
      { id: 'in', label: 'In', type: 'any', required: true }
    ],
    outputs: [
      { id: 'out', label: 'Out', type: 'any', required: false }
    ],
    tlangType: 'Strings.KebabCase',
    style: { color: '#10b981' }
  },

  'Objects.MapValues': {
    id: 'Objects.MapValues',
    name: 'MapValues',
    category: 'Objects',
    description: 'MapValuesNode - Transform all values in an object',
    inputs: [
      { id: 'in', label: 'In', type: 'string', required: true }
    ],
    outputs: [
      { id: 'out', label: 'Out', type: 'object', required: false }
    ],
    tlangType: 'Objects.MapValues',
    style: { color: '#f59e0b' }
  },

  'Objects.MapKeys': {
    id: 'Objects.MapKeys',
    name: 'MapKeys',
    category: 'Objects',
    description: 'MapKeysNode - Transform all keys in an object',
    inputs: [
      { id: 'in', label: 'In', type: 'string', required: true }
    ],
    outputs: [
      { id: 'out', label: 'Out', type: 'string', required: false }
    ],
    tlangType: 'Objects.MapKeys',
    style: { color: '#f59e0b' }
  },

  'Objects.Keys': {
    id: 'Objects.Keys',
    name: 'Keys',
    category: 'Objects',
    description: 'KeysNode - Get object keys as tuple',
    inputs: [
      { id: 'in', label: 'In', type: 'string', required: true }
    ],
    outputs: [
      { id: 'out', label: 'Out', type: 'array', required: false }
    ],
    tlangType: 'Objects.Keys',
    style: { color: '#f59e0b' }
  },

  'Objects.Values': {
    id: 'Objects.Values',
    name: 'Values',
    category: 'Objects',
    description: 'ValuesNode - Get object values as tuple',
    inputs: [
      { id: 'in', label: 'In', type: 'string', required: true }
    ],
    outputs: [
      { id: 'out', label: 'Out', type: 'array', required: false }
    ],
    tlangType: 'Objects.Values',
    style: { color: '#f59e0b' }
  },

  'Objects.Entries': {
    id: 'Objects.Entries',
    name: 'Entries',
    category: 'Objects',
    description: 'EntriesNode - Convert object to entries',
    inputs: [
      { id: 'in', label: 'In', type: 'string', required: true }
    ],
    outputs: [
      { id: 'out', label: 'Out', type: 'array', required: false }
    ],
    tlangType: 'Objects.Entries',
    style: { color: '#f59e0b' }
  },

  'Objects.FromEntries': {
    id: 'Objects.FromEntries',
    name: 'FromEntries',
    category: 'Objects',
    description: 'FromEntriesNode - Convert entries to object',
    inputs: [
      { id: 'in', label: 'In', type: 'array', required: true }
    ],
    outputs: [
      { id: 'out', label: 'Out', type: 'number', required: false }
    ],
    tlangType: 'Objects.FromEntries',
    style: { color: '#f59e0b' }
  },

  'Numbers.Add': {
    id: 'Numbers.Add',
    name: 'Add',
    category: 'Numbers',
    description: 'AddNode - Add two numbers',
    inputs: [
      { id: 'a', label: 'A', type: 'number', required: true },
      { id: 'b', label: 'B', type: 'number', required: true }
    ],
    outputs: [
      { id: 'sum', label: 'Sum', type: 'number', required: false }
    ],
    tlangType: 'Numbers.Add',
    style: { color: '#3b82f6' }
  },

  'Numbers.Sub': {
    id: 'Numbers.Sub',
    name: 'Sub',
    category: 'Numbers',
    description: 'SubNode - Subtract two numbers',
    inputs: [
      { id: 'a', label: 'A', type: 'number', required: true },
      { id: 'b', label: 'B', type: 'number', required: true }
    ],
    outputs: [
      { id: 'diff', label: 'Diff', type: 'number', required: false }
    ],
    tlangType: 'Numbers.Sub',
    style: { color: '#3b82f6' }
  },

  'Numbers.Mul': {
    id: 'Numbers.Mul',
    name: 'Mul',
    category: 'Numbers',
    description: 'MulNode - Multiply two numbers',
    inputs: [
      { id: 'a', label: 'A', type: 'number', required: true },
      { id: 'b', label: 'B', type: 'number', required: true }
    ],
    outputs: [
      { id: 'product', label: 'Product', type: 'any', required: false }
    ],
    tlangType: 'Numbers.Mul',
    style: { color: '#3b82f6' }
  },

  'Numbers.Div': {
    id: 'Numbers.Div',
    name: 'Div',
    category: 'Numbers',
    description: 'DivNode - Divide two numbers (integer division)',
    inputs: [
      { id: 'a', label: 'A', type: 'number', required: true },
      { id: 'b', label: 'B', type: 'number', required: true }
    ],
    outputs: [
      { id: 'quotient', label: 'Quotient', type: 'any', required: false }
    ],
    tlangType: 'Numbers.Div',
    style: { color: '#3b82f6' }
  },

  'Numbers.Mod': {
    id: 'Numbers.Mod',
    name: 'Mod',
    category: 'Numbers',
    description: 'ModNode - Modulo operation',
    inputs: [
      { id: 'a', label: 'A', type: 'number', required: true },
      { id: 'b', label: 'B', type: 'number', required: true }
    ],
    outputs: [
      { id: 'remainder', label: 'Remainder', type: 'any', required: false }
    ],
    tlangType: 'Numbers.Mod',
    style: { color: '#3b82f6' }
  },

  'Numbers.Negate': {
    id: 'Numbers.Negate',
    name: 'Negate',
    category: 'Numbers',
    description: 'NegateNode - Negate a number (not supported at type level, returns 0)',
    inputs: [
      { id: 'in', label: 'In', type: 'number', required: true }
    ],
    outputs: [
      { id: 'out', label: 'Out', type: 'any', required: false }
    ],
    tlangType: 'Numbers.Negate',
    style: { color: '#3b82f6' }
  },

  'Numbers.Abs': {
    id: 'Numbers.Abs',
    name: 'Abs',
    category: 'Numbers',
    description: 'AbsNode - Absolute value (identity for positive numbers)',
    inputs: [
      { id: 'in', label: 'In', type: 'number', required: true }
    ],
    outputs: [
      { id: 'out', label: 'Out', type: 'any', required: false }
    ],
    tlangType: 'Numbers.Abs',
    style: { color: '#3b82f6' }
  },

  'Numbers.Max': {
    id: 'Numbers.Max',
    name: 'Max',
    category: 'Numbers',
    description: 'MaxNode - Return maximum of two numbers',
    inputs: [
      { id: 'a', label: 'A', type: 'number', required: true },
      { id: 'b', label: 'B', type: 'number', required: true }
    ],
    outputs: [
      { id: 'max', label: 'Max', type: 'any', required: false }
    ],
    tlangType: 'Numbers.Max',
    style: { color: '#3b82f6' }
  },

  'Numbers.Min': {
    id: 'Numbers.Min',
    name: 'Min',
    category: 'Numbers',
    description: 'MinNode - Return minimum of two numbers',
    inputs: [
      { id: 'a', label: 'A', type: 'number', required: true },
      { id: 'b', label: 'B', type: 'number', required: true }
    ],
    outputs: [
      { id: 'min', label: 'Min', type: 'any', required: false }
    ],
    tlangType: 'Numbers.Min',
    style: { color: '#3b82f6' }
  },

  'Numbers.Compare': {
    id: 'Numbers.Compare',
    name: 'Compare',
    category: 'Numbers',
    description: 'CompareNode - Compare two numbers',
    inputs: [
      { id: 'a', label: 'A', type: 'number', required: true },
      { id: 'b', label: 'B', type: 'number', required: true }
    ],
    outputs: [
      { id: 'result', label: 'Result', type: 'any', required: false }
    ],
    tlangType: 'Numbers.Compare',
    style: { color: '#3b82f6' }
  },

  'Numbers.Equal': {
    id: 'Numbers.Equal',
    name: 'Equal',
    category: 'Numbers',
    description: 'EqualNode - Check if two numbers are equal',
    inputs: [
      { id: 'a', label: 'A', type: 'number', required: true },
      { id: 'b', label: 'B', type: 'number', required: true }
    ],
    outputs: [
      { id: 'result', label: 'Result', type: 'any', required: false }
    ],
    tlangType: 'Numbers.Equal',
    style: { color: '#3b82f6' }
  },

  'Numbers.LessThan': {
    id: 'Numbers.LessThan',
    name: 'LessThan',
    category: 'Numbers',
    description: 'LessThanNode - Check if a < b',
    inputs: [
      { id: 'a', label: 'A', type: 'number', required: true },
      { id: 'b', label: 'B', type: 'number', required: true }
    ],
    outputs: [
      { id: 'result', label: 'Result', type: 'any', required: false }
    ],
    tlangType: 'Numbers.LessThan',
    style: { color: '#3b82f6' }
  },

  'Numbers.GreaterThan': {
    id: 'Numbers.GreaterThan',
    name: 'GreaterThan',
    category: 'Numbers',
    description: 'GreaterThanNode - Check if a > b',
    inputs: [
      { id: 'a', label: 'A', type: 'number', required: true },
      { id: 'b', label: 'B', type: 'number', required: true }
    ],
    outputs: [
      { id: 'result', label: 'Result', type: 'any', required: false }
    ],
    tlangType: 'Numbers.GreaterThan',
    style: { color: '#3b82f6' }
  },

  'Booleans.And': {
    id: 'Booleans.And',
    name: 'And',
    category: 'Booleans',
    description: 'AndNode - Logical AND of two booleans',
    inputs: [
      { id: 'a', label: 'A', type: 'boolean', required: true },
      { id: 'b', label: 'B', type: 'boolean', required: true }
    ],
    outputs: [
      { id: 'result', label: 'Result', type: 'any', required: false }
    ],
    tlangType: 'Booleans.And',
    style: { color: '#8b5cf6' }
  },

  'Booleans.Or': {
    id: 'Booleans.Or',
    name: 'Or',
    category: 'Booleans',
    description: 'OrNode - Logical OR of two booleans',
    inputs: [
      { id: 'a', label: 'A', type: 'boolean', required: true },
      { id: 'b', label: 'B', type: 'boolean', required: true }
    ],
    outputs: [
      { id: 'result', label: 'Result', type: 'any', required: false }
    ],
    tlangType: 'Booleans.Or',
    style: { color: '#8b5cf6' }
  },

  'Booleans.Not': {
    id: 'Booleans.Not',
    name: 'Not',
    category: 'Booleans',
    description: 'NotNode - Logical NOT',
    inputs: [
      { id: 'in', label: 'In', type: 'boolean', required: true }
    ],
    outputs: [
      { id: 'out', label: 'Out', type: 'any', required: false }
    ],
    tlangType: 'Booleans.Not',
    style: { color: '#8b5cf6' }
  },

  'Booleans.Equals': {
    id: 'Booleans.Equals',
    name: 'Equals',
    category: 'Booleans',
    description: 'EqualsNode - Check if two booleans are equal',
    inputs: [
      { id: 'a', label: 'A', type: 'boolean', required: true },
      { id: 'b', label: 'B', type: 'boolean', required: true }
    ],
    outputs: [
      { id: 'result', label: 'Result', type: 'any', required: false }
    ],
    tlangType: 'Booleans.Equals',
    style: { color: '#8b5cf6' }
  },

  'Booleans.Xor': {
    id: 'Booleans.Xor',
    name: 'Xor',
    category: 'Booleans',
    description: 'XorNode - Logical XOR (exclusive or)',
    inputs: [
      { id: 'a', label: 'A', type: 'boolean', required: true },
      { id: 'b', label: 'B', type: 'boolean', required: true }
    ],
    outputs: [
      { id: 'result', label: 'Result', type: 'any', required: false }
    ],
    tlangType: 'Booleans.Xor',
    style: { color: '#8b5cf6' }
  },

  'Match.Match': {
    id: 'Match.Match',
    name: 'Match',
    category: 'Match',
    description: 'MatchNode - Pattern matching with multiple clauses',
    inputs: [
      { id: 'in', label: 'In', type: 'any', required: true }
    ],
    outputs: [
      { id: 'out', label: 'Out', type: 'any', required: false }
    ],
    tlangType: 'Match.Match',
    style: { color: '#f97316' }
  },

  'Functions.Parameters': {
    id: 'Functions.Parameters',
    name: 'Parameters',
    category: 'Functions',
    description: 'ParametersNode - Extract function parameters',
    inputs: [
      { id: 'in', label: 'In', type: 'any', required: true }
    ],
    outputs: [
      { id: 'out', label: 'Out', type: 'any', required: false }
    ],
    tlangType: 'Functions.Parameters',
    style: { color: '#14b8a6' }
  },

  'Functions.ReturnType': {
    id: 'Functions.ReturnType',
    name: 'ReturnType',
    category: 'Functions',
    description: 'ReturnTypeNode - Extract function return type',
    inputs: [
      { id: 'in', label: 'In', type: 'any', required: true }
    ],
    outputs: [
      { id: 'out', label: 'Out', type: 'any', required: false }
    ],
    tlangType: 'Functions.ReturnType',
    style: { color: '#14b8a6' }
  },

  'Functions.MapReturnType': {
    id: 'Functions.MapReturnType',
    name: 'MapReturnType',
    category: 'Functions',
    description: 'MapReturnTypeNode - Transform return type of a function',
    inputs: [
      { id: 'in', label: 'In', type: 'any', required: true }
    ],
    outputs: [
      { id: 'out', label: 'Out', type: 'object', required: false }
    ],
    tlangType: 'Functions.MapReturnType',
    style: { color: '#14b8a6' }
  },

  'Functions.Constant': {
    id: 'Functions.Constant',
    name: 'Constant',
    category: 'Functions',
    description: 'ConstantNode - Always return a constant value',
    inputs: [
      { id: 'in', label: 'In', type: 'any', required: true }
    ],
    outputs: [
      { id: 'out', label: 'Out', type: 'any', required: false }
    ],
    tlangType: 'Functions.Constant',
    style: { color: '#14b8a6' }
  }
}

/**
 * Get all nodes for a specific category
 */
export function getNodesByCategory(category: string): TLangNodeMetadata[] {
  return Object.values(nodeRegistry).filter(node => node.category === category)
}

/**
 * Get all unique categories
 */
export function getAllCategories(): string[] {
  const categories = new Set<string>()
  Object.values(nodeRegistry).forEach(node => categories.add(node.category))
  return Array.from(categories).sort()
}

/**
 * Get a node by its ID
 */
export function getNodeById(id: string): TLangNodeMetadata | undefined {
  return nodeRegistry[id]
}
